{
  "services": {
    "uas": {
      "image": "no_crash:local-nvidia",
      "pull_policy": "never",
      "platform": "linux/amd64",
      "build": {
        "context": "..",
        "dockerfile": ".devcontainer/Dockerfile",
        "target": "nvidia",
        "args": {
          "BUILD_JOBS": "${NO_CRASH_BUILD_JOBS:-4}"
        }
      }
    }
  }
}
